# Generated by Django 4.2.4 on 2023-08-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_bulletin_category_alter_bulletin_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin',
            old_name='category',
            new_name='cat',
        ),
    ]
