# Generated by Django 4.2.4 on 2023-09-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_bulletin_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
